### ISSUE TITLE
13.0.2 Support?

### ISSUE THREAD

**Issue by JunoAndIce** [ThatNintendoNerd/stage_divetoheart#1]
This plugin is now outdated as of 13.0.2. Any chance on an update?

**Comment by ThatNintendoNerd** [comment]
I was made aware of the fact that some of its features no longer work correctly on 13.0.2. I hand-checked the bytecode used for offset searching and it appears the only feature that broke is being able to use Dive to the Heart with stage hazards off. I have plans to update the plugin beyond just compatibility with 13.0.2. I just haven't decided if I want to push a compatibility update first and then the major update afterward or combine the two.

**Comment by ThatNintendoNerd** [comment]
Fixed as of [v2.0.0](https://github.com/ThatNintendoNerd/stage_divetoheart/releases/tag/v2.0.0).

**Comment by JunoAndIce** [comment]
Hey sorry if I feel like I'm bugging you, but I really like this mod. Any chance for a 13.0.3 update?

**Comment by ThatNintendoNerd** [comment]
The mod does not need to be updated for Ver. 13.0.3 thanks to its reliable offset searching.
